export const wrestlingData = {
  WWE: {
    brands: [
      { name: "Raw", color: "bg-red-600/20 border-red-500/30 text-red-400" },
      { name: "SmackDown", color: "bg-blue-600/20 border-blue-500/30 text-blue-400" },
      { name: "NXT", color: "bg-yellow-600/20 border-yellow-500/30 text-yellow-400" },
    ],
    colors: {
      primary: "bg-gradient-to-r from-yellow-500 to-yellow-600",
      secondary: "bg-red-600/10 border-red-500/20",
      accent: "text-yellow-400 border-yellow-500/30",
    },
    wrestlers: [
      // Raw Brand - Updated 2025 Roster
      { name: "Cody Rhodes", brand: "Raw", status: "Active" },
      { name: "Seth Rollins", brand: "Raw", status: "Active" },
      { name: "Drew McIntyre", brand: "Raw", status: "Active" },
      { name: "CM Punk", brand: "Raw", status: "Active" },
      { name: "Damian Priest", brand: "Raw", status: "Active" },
      { name: "Jey Uso", brand: "Raw", status: "Active" },
      { name: "Jimmy Uso", brand: "Raw", status: "Active" },
      { name: "Finn Balor", brand: "Raw", status: "Active" },
      { name: "JD McDonagh", brand: "Raw", status: "Active" },
      { name: "Dominik Mysterio", brand: "Raw", status: "Active" },
      { name: "Rey Mysterio", brand: "Raw", status: "Active" },
      { name: "Carlito", brand: "Raw", status: "Active" },
      { name: "Chad Gable", brand: "Raw", status: "Active" },
      { name: "Otis", brand: "Raw", status: "Active" },
      { name: "Akira Tozawa", brand: "Raw", status: "Active" },
      { name: "Braun Strowman", brand: "Raw", status: "Active" },
      { name: "Bronson Reed", brand: "Raw", status: "Active" },
      { name: "Ilja Dragunov", brand: "Raw", status: "Active" },
      { name: "Pete Dunne", brand: "Raw", status: "Active" },
      { name: "Tyler Bate", brand: "Raw", status: "Active" },
      { name: "Kofi Kingston", brand: "Raw", status: "Active" },
      { name: "Xavier Woods", brand: "Raw", status: "Active" },
      { name: "R-Truth", brand: "Raw", status: "Active" },
      { name: "The Miz", brand: "Raw", status: "Active" },

      // Raw Women
      { name: "Rhea Ripley", brand: "Raw", status: "Active" },
      { name: "Liv Morgan", brand: "Raw", status: "Active" },
      { name: "Bianca Belair", brand: "Raw", status: "Active" },
      { name: "Shayna Baszler", brand: "Raw", status: "Active" },
      { name: "Zoey Stark", brand: "Raw", status: "Active" },
      { name: "Natalya", brand: "Raw", status: "Active" },
      { name: "Piper Niven", brand: "Raw", status: "Active" },
      { name: "Lyra Valkyria", brand: "Raw", status: "Active" },
      { name: "Zelina Vega", brand: "Raw", status: "Active" },
      { name: "Ivy Nile", brand: "Raw", status: "Active" },
      { name: "Maxxine Dupri", brand: "Raw", status: "Active" },

      // SmackDown Brand - Updated 2025 Roster
      { name: "Roman Reigns", brand: "SmackDown", status: "Active" },
      { name: "Solo Sikoa", brand: "SmackDown", status: "Active" },
      { name: "Jacob Fatu", brand: "SmackDown", status: "Active" },
      { name: "Tama Tonga", brand: "SmackDown", status: "Active" },
      { name: "Tonga Loa", brand: "SmackDown", status: "Active" },
      { name: "LA Knight", brand: "SmackDown", status: "Active" },
      { name: "Kevin Owens", brand: "SmackDown", status: "Active" },
      { name: "Randy Orton", brand: "SmackDown", status: "Active" },
      { name: "Gunther", brand: "SmackDown", status: "Active" },
      { name: "Ludwig Kaiser", brand: "SmackDown", status: "Active" },
      { name: "Giovanni Vinci", brand: "SmackDown", status: "Active" },
      { name: "Sheamus", brand: "SmackDown", status: "Active" },
      { name: "Apollo Crews", brand: "SmackDown", status: "Active" },
      { name: "Dragon Lee", brand: "SmackDown", status: "Active" },
      { name: "Santos Escobar", brand: "SmackDown", status: "Active" },
      { name: "Cruz Del Toro", brand: "SmackDown", status: "Active" },
      { name: "Joaquin Wilde", brand: "SmackDown", status: "Active" },
      { name: "Andrade", brand: "SmackDown", status: "Active" },
      { name: "Karrion Kross", brand: "SmackDown", status: "Active" },
      { name: "Shinsuke Nakamura", brand: "SmackDown", status: "Active" },
      { name: "Ricochet", brand: "SmackDown", status: "Active" },

      // SmackDown Women
      { name: "Bayley", brand: "SmackDown", status: "Active" },
      { name: "IYO SKY", brand: "SmackDown", status: "Active" },
      { name: "Nia Jax", brand: "SmackDown", status: "Active" },
      { name: "Tiffany Stratton", brand: "SmackDown", status: "Active" },
      { name: "Jade Cargill", brand: "SmackDown", status: "Active" },
      { name: "Raquel Rodriguez", brand: "SmackDown", status: "Active" },
      { name: "Dakota Kai", brand: "SmackDown", status: "Active" },
      { name: "Naomi", brand: "SmackDown", status: "Active" },
      { name: "Michin", brand: "SmackDown", status: "Active" },
      { name: "Chelsea Green", brand: "SmackDown", status: "Active" },
      { name: "Blair Davenport", brand: "SmackDown", status: "Active" },

      // NXT Brand - Updated 2025 Roster
      { name: "Trick Williams", brand: "NXT", status: "Active" },
      { name: "Carmelo Hayes", brand: "NXT", status: "Active" },
      { name: "Bron Breakker", brand: "NXT", status: "Active" },
      { name: "Grayson Waller", brand: "NXT", status: "Active" },
      { name: "Austin Theory", brand: "NXT", status: "Active" },
      { name: "Tony D'Angelo", brand: "NXT", status: "Active" },
      { name: "Axiom", brand: "NXT", status: "Active" },
      { name: "Nathan Frazer", brand: "NXT", status: "Active" },
      { name: "Wes Lee", brand: "NXT", status: "Active" },
      { name: "Joe Coffey", brand: "NXT", status: "Active" },
      { name: "Mark Coffey", brand: "NXT", status: "Active" },
      { name: "Wolfgang", brand: "NXT", status: "Active" },
      { name: "Lexis King", brand: "NXT", status: "Active" },
      { name: "Je'Von Evans", brand: "NXT", status: "Active" },
      { name: "Oba Femi", brand: "NXT", status: "Active" },

      // NXT Women
      { name: "Roxanne Perez", brand: "NXT", status: "Active" },
      { name: "Cora Jade", brand: "NXT", status: "Active" },
      { name: "Kelani Jordan", brand: "NXT", status: "Active" },
      { name: "Lash Legend", brand: "NXT", status: "Active" },
      { name: "Jakara Jackson", brand: "NXT", status: "Active" },
      { name: "Fallon Henley", brand: "NXT", status: "Active" },
      { name: "Jacy Jayne", brand: "NXT", status: "Active" },
      { name: "Thea Hail", brand: "NXT", status: "Active" },
      { name: "Sol Ruca", brand: "NXT", status: "Active" },

      // Part-Time/Legends
      { name: "John Cena", brand: "Raw", status: "Part-Time" },
      { name: "Brock Lesnar", brand: "SmackDown", status: "Part-Time" },
      { name: "The Rock", brand: "SmackDown", status: "Part-Time" },
      { name: "Logan Paul", brand: "SmackDown", status: "Part-Time" },
      { name: "The Undertaker", brand: "Raw", status: "Legend" },
      { name: "Triple H", brand: "Raw", status: "Legend" },
      { name: "Shawn Michaels", brand: "NXT", status: "Legend" },
    ],
    events: [
      "Royal Rumble",
      "Elimination Chamber",
      "WrestleMania",
      "Backlash",
      "King of the Ring",
      "Money in the Bank",
      "SummerSlam",
      "Clash at the Castle",
      "Bad Blood",
      "Crown Jewel",
      "Survivor Series",
      "Saturday Night's Main Event",
      "Raw",
      "SmackDown",
      "NXT",
    ],
  },

  AEW: {
    brands: [
      { name: "Dynamite", color: "bg-yellow-600/20 border-yellow-500/30 text-yellow-400" },
      { name: "Rampage", color: "bg-red-600/20 border-red-500/30 text-red-400" },
      { name: "Collision", color: "bg-blue-600/20 border-blue-500/30 text-blue-400" },
    ],
    colors: {
      primary: "bg-gradient-to-r from-yellow-400 to-red-500",
      secondary: "bg-black/20 border-yellow-500/20",
      accent: "text-yellow-400 border-red-500/30",
    },
    wrestlers: [
      // Main Event Stars
      { name: "Jon Moxley", brand: "Dynamite", status: "Active" },
      { name: "Orange Cassidy", brand: "Dynamite", status: "Active" },
      { name: "Will Ospreay", brand: "Dynamite", status: "Active" },
      { name: "MJF", brand: "Dynamite", status: "Active" },
      { name: "Adam Cole", brand: "Dynamite", status: "Active" },
      { name: "Hangman Page", brand: "Dynamite", status: "Active" },
      { name: "Kenny Omega", brand: "Dynamite", status: "Part-Time" },
      { name: "Eddie Kingston", brand: "Collision", status: "Active" },
      { name: "Darby Allin", brand: "Dynamite", status: "Active" },
      { name: "Jungle Boy", brand: "Collision", status: "Active" },
      { name: "Sammy Guevara", brand: "Rampage", status: "Active" },
      { name: "Wardlow", brand: "Rampage", status: "Active" },
      { name: "Powerhouse Hobbs", brand: "Collision", status: "Active" },
      { name: "Ricky Starks", brand: "Collision", status: "Active" },
      { name: "Chris Jericho", brand: "Dynamite", status: "Active" },
      { name: "Claudio Castagnoli", brand: "Collision", status: "Active" },
      { name: "Wheeler Yuta", brand: "Collision", status: "Active" },
      { name: "Daniel Garcia", brand: "Dynamite", status: "Active" },
      { name: "Matt Menard", brand: "Rampage", status: "Active" },
      { name: "Angelo Parker", brand: "Rampage", status: "Active" },
      { name: "Jake Hager", brand: "Dynamite", status: "Active" },
      { name: "Konosuke Takeshita", brand: "Dynamite", status: "Active" },
      { name: "Kyle Fletcher", brand: "Collision", status: "Active" },
      { name: "Mark Briscoe", brand: "Collision", status: "Active" },
      { name: "FTR Cash", brand: "Collision", status: "Active" },
      { name: "FTR Dax", brand: "Collision", status: "Active" },
      { name: "The Young Bucks Matt", brand: "Dynamite", status: "Active" },
      { name: "The Young Bucks Nick", brand: "Dynamite", status: "Active" },
      { name: "Kazuchika Okada", brand: "Dynamite", status: "Active" },
      { name: "Swerve Strickland", brand: "Dynamite", status: "Active" },
      { name: "Keith Lee", brand: "Collision", status: "Active" },
      { name: "Dustin Rhodes", brand: "Collision", status: "Active" },

      // Women's Division
      { name: "Toni Storm", brand: "Dynamite", status: "Active" },
      { name: "Mariah May", brand: "Dynamite", status: "Active" },
      { name: "Britt Baker", brand: "Dynamite", status: "Active" },
      { name: "Jamie Hayter", brand: "Dynamite", status: "Active" },
      { name: "Hikaru Shida", brand: "Rampage", status: "Active" },
      { name: "Thunder Rosa", brand: "Collision", status: "Active" },
      { name: "Ruby Soho", brand: "Rampage", status: "Active" },
      { name: "Kris Statlander", brand: "Collision", status: "Active" },
      { name: "Willow Nightingale", brand: "Collision", status: "Active" },
      { name: "Skye Blue", brand: "Rampage", status: "Active" },
      { name: "Anna Jay", brand: "Collision", status: "Active" },
      { name: "Tay Melo", brand: "Rampage", status: "Active" },
      { name: "Mercedes Mone", brand: "Dynamite", status: "Active" },
      { name: "Kamille", brand: "Dynamite", status: "Active" },
      { name: "Serena Deeb", brand: "Collision", status: "Active" },
      { name: "Penelope Ford", brand: "Rampage", status: "Active" },
      { name: "Abadon", brand: "Rampage", status: "Active" },

      // Part-Time/Legends
      { name: "Sting", brand: "Dynamite", status: "Legend" },
      { name: "Jeff Hardy", brand: "Dynamite", status: "Part-Time" },
      { name: "Matt Hardy", brand: "Dynamite", status: "Part-Time" },
      { name: "Christian Cage", brand: "Collision", status: "Active" },
    ],
    events: [
      "Revolution",
      "Double or Nothing",
      "Forbidden Door",
      "All Out",
      "Full Gear",
      "All In",
      "Grand Slam",
      "Winter is Coming",
      "Fight for the Fallen",
      "Fyter Fest",
      "Dynamite",
      "Rampage",
      "Collision",
    ],
  },

  NJPW: {
    brands: [
      { name: "Strong", color: "bg-red-600/20 border-red-500/30 text-red-400" },
      { name: "World", color: "bg-white/20 border-white/30 text-white" },
    ],
    colors: {
      primary: "bg-gradient-to-r from-red-600 to-white",
      secondary: "bg-red-600/10 border-red-500/20",
      accent: "text-red-400 border-white/30",
    },
    wrestlers: [
      { name: "Kazuchika Okada", brand: "World", status: "Active" },
      { name: "Will Ospreay", brand: "World", status: "Active" },
      { name: "Hiroshi Tanahashi", brand: "World", status: "Active" },
      { name: "Kota Ibushi", brand: "World", status: "Part-Time" },
      { name: "Jay White", brand: "Strong", status: "Active" },
      { name: "Tetsuya Naito", brand: "World", status: "Active" },
      { name: "Shingo Takagi", brand: "World", status: "Active" },
      { name: "Sanada", brand: "World", status: "Active" },
      { name: "Evil", brand: "World", status: "Active" },
      { name: "Hiromu Takahashi", brand: "World", status: "Active" },
      { name: "Tomohiro Ishii", brand: "Strong", status: "Active" },
      { name: "Toru Yano", brand: "World", status: "Active" },
      { name: "Juice Robinson", brand: "Strong", status: "Active" },
      { name: "David Finlay", brand: "Strong", status: "Active" },
      { name: "Taiji Ishimori", brand: "World", status: "Active" },
      { name: "El Desperado", brand: "World", status: "Active" },
      { name: "Robbie Eagles", brand: "Strong", status: "Active" },
      { name: "Master Wato", brand: "World", status: "Active" },
      { name: "Zack Sabre Jr", brand: "World", status: "Active" },
      { name: "Taichi", brand: "World", status: "Active" },
      { name: "Tama Tonga", brand: "Strong", status: "Active" },
      { name: "Tanga Loa", brand: "Strong", status: "Active" },
      { name: "Hikuleo", brand: "Strong", status: "Active" },
      { name: "Chase Owens", brand: "Strong", status: "Active" },
      { name: "Bad Luck Fale", brand: "Strong", status: "Active" },
    ],
    events: [
      "Wrestle Kingdom",
      "New Beginning",
      "Sakura Genesis",
      "Wrestling Dontaku",
      "Best of the Super Juniors",
      "Dominion",
      "G1 Climax",
      "Royal Quest",
      "Destruction",
      "King of Pro Wrestling",
      "Power Struggle",
      "World Tag League",
    ],
  },

  TNA: {
    brands: [{ name: "Impact", color: "bg-blue-600/20 border-blue-500/30 text-blue-400" }],
    colors: {
      primary: "bg-gradient-to-r from-blue-600 to-red-500",
      secondary: "bg-blue-600/10 border-blue-500/20",
      accent: "text-blue-400 border-red-500/30",
    },
    wrestlers: [
      { name: "Moose", brand: "Impact", status: "Active" },
      { name: "Eddie Edwards", brand: "Impact", status: "Active" },
      { name: "Rich Swann", brand: "Impact", status: "Active" },
      { name: "Willie Mack", brand: "Impact", status: "Active" },
      { name: "Sami Callihan", brand: "Impact", status: "Active" },
      { name: "Jake Something", brand: "Impact", status: "Active" },
      { name: "Rhino", brand: "Impact", status: "Part-Time" },
      { name: "Tommy Dreamer", brand: "Impact", status: "Part-Time" },
      { name: "Jordynne Grace", brand: "Impact", status: "Active" },
      { name: "Deonna Purrazzo", brand: "Impact", status: "Active" },
      { name: "Chris Sabin", brand: "Impact", status: "Active" },
      { name: "Alex Shelley", brand: "Impact", status: "Active" },
      { name: "Ace Austin", brand: "Impact", status: "Active" },
      { name: "Madman Fulton", brand: "Impact", status: "Active" },
      { name: "Rohit Raju", brand: "Impact", status: "Active" },
      { name: "Rosemary", brand: "Impact", status: "Active" },
      { name: "Havok", brand: "Impact", status: "Active" },
      { name: "Su Yung", brand: "Impact", status: "Active" },
      { name: "Alisha Edwards", brand: "Impact", status: "Active" },
      { name: "Tenille Dashwood", brand: "Impact", status: "Active" },
      { name: "Nic Nemeth", brand: "Impact", status: "Active" },
      { name: "Joe Hendry", brand: "Impact", status: "Active" },
      { name: "PCO", brand: "Impact", status: "Active" },
      { name: "Steph De Lander", brand: "Impact", status: "Active" },
    ],
    events: [
      "Genesis",
      "No Surrender",
      "Rebellion",
      "Under Siege",
      "Slammiversary",
      "Emergence",
      "Victory Road",
      "Bound for Glory",
      "Turning Point",
      "Final Resolution",
      "Impact Wrestling",
    ],
  },

  ROH: {
    brands: [{ name: "Honor Club", color: "bg-yellow-600/20 border-yellow-500/30 text-yellow-400" }],
    colors: {
      primary: "bg-gradient-to-r from-yellow-500 to-blue-600",
      secondary: "bg-yellow-600/10 border-yellow-500/20",
      accent: "text-yellow-400 border-blue-500/30",
    },
    wrestlers: [
      { name: "Jonathan Gresham", brand: "Honor Club", status: "Active" },
      { name: "Bandido", brand: "Honor Club", status: "Active" },
      { name: "Rush", brand: "Honor Club", status: "Active" },
      { name: "Dragon Lee", brand: "Honor Club", status: "Active" },
      { name: "Rey Horus", brand: "Honor Club", status: "Active" },
      { name: "Flamita", brand: "Honor Club", status: "Active" },
      { name: "Dalton Castle", brand: "Honor Club", status: "Active" },
      { name: "The Briscoes Jay", brand: "Honor Club", status: "Active" },
      { name: "The Briscoes Mark", brand: "Honor Club", status: "Active" },
      { name: "Mercedes Martinez", brand: "Honor Club", status: "Active" },
      { name: "Willow Nightingale", brand: "Honor Club", status: "Active" },
      { name: "Athena", brand: "Honor Club", status: "Active" },
      { name: "Red Velvet", brand: "Honor Club", status: "Active" },
      { name: "Leyla Hirsch", brand: "Honor Club", status: "Active" },
      { name: "Tony Nese", brand: "Honor Club", status: "Active" },
      { name: "Brian Cage", brand: "Honor Club", status: "Active" },
      { name: "Lee Moriarty", brand: "Honor Club", status: "Active" },
      { name: "Daniel Garcia", brand: "Honor Club", status: "Active" },
    ],
    events: [
      "Honor Reigns Supreme",
      "Supercard of Honor",
      "Death Before Dishonor",
      "Glory by Honor",
      "Final Battle",
      "Honor Club",
    ],
  },

  Other: {
    brands: [{ name: "Independent", color: "bg-purple-600/20 border-purple-500/30 text-purple-400" }],
    colors: {
      primary: "bg-gradient-to-r from-purple-500 to-pink-500",
      secondary: "bg-purple-600/10 border-purple-500/20",
      accent: "text-purple-400 border-pink-500/30",
    },
    wrestlers: [
      { name: "CM Punk", brand: "Independent", status: "Active" },
      { name: "Daniel Bryan", brand: "Independent", status: "Active" },
      { name: "Kevin Steen", brand: "Independent", status: "Active" },
      { name: "El Generico", brand: "Independent", status: "Active" },
      { name: "Adam Cole", brand: "Independent", status: "Active" },
      { name: "Kyle O'Reilly", brand: "Independent", status: "Active" },
      { name: "Bobby Fish", brand: "Independent", status: "Active" },
      { name: "Roderick Strong", brand: "Independent", status: "Active" },
      { name: "Keith Lee", brand: "Independent", status: "Active" },
      { name: "Dijak", brand: "Independent", status: "Active" },
    ],
    events: ["Custom Event"],
  },
}

// Add smart match type configurations
export const matchTypeConfigs = {
  "Men's Royal Rumble": {
    participants: 30,
    singleWinner: true,
    genderFilter: "male",
    teamBased: false,
  },
  "Women's Royal Rumble": {
    participants: 30,
    singleWinner: true,
    genderFilter: "female",
    teamBased: false,
  },
  "Men's Battle Royal": {
    participants: 20,
    singleWinner: true,
    genderFilter: "male",
    teamBased: false,
  },
  "Women's Battle Royal": {
    participants: 20,
    singleWinner: true,
    genderFilter: "female",
    teamBased: false,
  },
  "War Games": {
    participants: 8,
    singleWinner: false,
    teamBased: true,
    teams: 2,
    playersPerTeam: 4,
  },
  "Men's Elimination Chamber": {
    participants: 6,
    singleWinner: true,
    genderFilter: "male",
    teamBased: false,
  },
  "Women's Elimination Chamber": {
    participants: 6,
    singleWinner: true,
    genderFilter: "female",
    teamBased: false,
  },
  "Men's Money in the Bank Ladder Match": {
    participants: 8,
    singleWinner: true,
    genderFilter: "male",
    teamBased: false,
  },
  "Women's Money in the Bank Ladder Match": {
    participants: 8,
    singleWinner: true,
    genderFilter: "female",
    teamBased: false,
  },
  "Tag Team Match": {
    participants: 4,
    singleWinner: false,
    teamBased: true,
    teams: 2,
    playersPerTeam: 2,
  },
  "Triple Threat": {
    participants: 3,
    singleWinner: false,
    teamBased: false,
  },
  "Fatal 4-Way": {
    participants: 4,
    singleWinner: false,
    teamBased: false,
  },
}

// Add gender detection for wrestlers (simplified approach)
export const getWrestlerGender = (wrestlerName: string): string => {
  const femaleWrestlers = [
    "Rhea Ripley",
    "Liv Morgan",
    "Bianca Belair",
    "Shayna Baszler",
    "Zoey Stark",
    "Natalya",
    "Piper Niven",
    "Lyra Valkyria",
    "Zelina Vega",
    "Ivy Nile",
    "Maxxine Dupri",
    "Bayley",
    "IYO SKY",
    "Nia Jax",
    "Tiffany Stratton",
    "Jade Cargill",
    "Raquel Rodriguez",
    "Dakota Kai",
    "Naomi",
    "Michin",
    "Chelsea Green",
    "Blair Davenport",
    "Roxanne Perez",
    "Cora Jade",
    "Kelani Jordan",
    "Lash Legend",
    "Jakara Jackson",
    "Fallon Henley",
    "Jacy Jayne",
    "Thea Hail",
    "Sol Ruca",
    "Toni Storm",
    "Mariah May",
    "Britt Baker",
    "Jamie Hayter",
    "Hikaru Shida",
    "Thunder Rosa",
    "Ruby Soho",
    "Kris Statlander",
    "Willow Nightingale",
    "Skye Blue",
    "Anna Jay",
    "Tay Melo",
    "Mercedes Mone",
    "Kamille",
    "Serena Deeb",
    "Penelope Ford",
    "Abadon",
    "Jordynne Grace",
    "Deonna Purrazzo",
    "Rosemary",
    "Havok",
    "Su Yung",
    "Alisha Edwards",
    "Tenille Dashwood",
    "Steph De Lander",
    "Mercedes Martinez",
    "Athena",
    "Red Velvet",
    "Leyla Hirsch",
  ]

  return femaleWrestlers.includes(wrestlerName) ? "female" : "male"
}

export const promotionMatchTypes = {
  WWE: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Hell in a Cell",
    "Ladder Match",
    "Tables Match",
    "TLC Match",
    "Last Man Standing",
    "I Quit Match",
    "Submission Match",
    "Iron Man Match",
    "Men's Royal Rumble",
    "Women's Royal Rumble",
    "Battle Royal",
    "Men's Elimination Chamber",
    "Women's Elimination Chamber",
    "War Games",
    "Men's Money in the Bank Ladder Match",
    "Women's Money in the Bank Ladder Match",
    "Casket Match",
    "Buried Alive Match",
    "Inferno Match",
    "Ambulance Match",
    "Punjabi Prison Match",
    "Extreme Rules Match",
  ],

  AEW: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Ladder Match",
    "Tables Match",
    "No Disqualification",
    "Last Man Standing",
    "I Quit Match",
    "Submission Match",
    "Iron Man Match",
    "Men's Battle Royal",
    "Women's Battle Royal",
    "Men's Casino Battle Royal",
    "Women's Casino Battle Royal",
    "Stadium Stampede",
    "Lights Out Match",
    "Unsanctioned Match",
    "Dog Collar Match",
    "Barbed Wire Deathmatch",
    "Exploding Barbed Wire Deathmatch",
    "Texas Deathmatch",
    "Coffin Match",
    "Blindfold Match",
    "Arcade Anarchy",
  ],

  NJPW: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Ladder Match",
    "No Disqualification",
    "Last Man Standing",
    "Submission Match",
    "Iron Man Match",
    "Battle Royal",
    "Lumberjack Match",
    "Hair vs Hair Match",
    "Mask vs Mask Match",
    "Loser Leaves Town",
    "Gauntlet Match",
    "Tournament Match",
  ],

  TNA: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Ladder Match",
    "Tables Match",
    "No Disqualification",
    "Last Man Standing",
    "I Quit Match",
    "Submission Match",
    "Iron Man Match",
    "Battle Royal",
    "Ultimate X Match",
    "King of the Mountain",
    "Monster's Ball",
    "Bound for Glory Series",
    "Feast or Fired",
    "Lockdown Steel Cage",
    "Six Sides of Steel",
  ],

  ROH: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Ladder Match",
    "Tables Match",
    "No Disqualification",
    "Last Man Standing",
    "I Quit Match",
    "Submission Match",
    "Iron Man Match",
    "Battle Royal",
    "Pure Wrestling Match",
    "Fight Without Honor",
    "Scramble Match",
    "Top Prospect Tournament",
  ],

  Other: [
    "Singles Match",
    "Championship Match",
    "Tag Team Match",
    "Triple Threat",
    "Fatal 4-Way",
    "Steel Cage",
    "Ladder Match",
    "Tables Match",
    "No Disqualification",
    "Last Man Standing",
    "Battle Royal",
    "Hardcore Match",
    "Death Match",
    "Intergender Match",
  ],
}

export const matchTypeDefaults = {
  "Men's Royal Rumble": { participants: 30, singleWinner: true },
  "Women's Royal Rumble": { participants: 30, singleWinner: true },
  "Men's Battle Royal": { participants: 20, singleWinner: true },
  "Women's Battle Royal": { participants: 20, singleWinner: true },
  "Men's Casino Battle Royal": { participants: 21, singleWinner: true },
  "Women's Casino Battle Royal": { participants: 21, singleWinner: true },
  "Battle Royal": { participants: 20, singleWinner: true },
  "Men's Elimination Chamber": { participants: 6, singleWinner: true },
  "Women's Elimination Chamber": { participants: 6, singleWinner: true },
  "War Games": { participants: 8, singleWinner: false },
  "Men's Money in the Bank Ladder Match": { participants: 8, singleWinner: true },
  "Women's Money in the Bank Ladder Match": { participants: 8, singleWinner: true },
  "Ultimate X Match": { participants: 6, singleWinner: true },
  "King of the Mountain": { participants: 5, singleWinner: true },
  "Gauntlet Match": { participants: 6, singleWinner: true },
}

export const sampleEvents = {
  WWE: {
    eventName: "Royal Rumble 2025",
    matches: [
      {
        wrestler1: "Roman Reigns",
        wrestler2: "Cody Rhodes",
        matchType: "Championship Match",
        championship: "WWE Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Rhea Ripley",
        wrestler2: "Liv Morgan",
        matchType: "Championship Match",
        championship: "Women's World Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Royal Rumble Winner",
        wrestler2: "",
        matchType: "Men's Royal Rumble",
        winner: null,
        participantCount: 30,
      },
      {
        wrestler1: "Royal Rumble Winner",
        wrestler2: "",
        matchType: "Women's Royal Rumble",
        winner: null,
        participantCount: 30,
      },
    ],
  },

  AEW: {
    eventName: "All In Texas 2025",
    matches: [
      {
        wrestler1: "Jon Moxley",
        wrestler2: "Will Ospreay",
        matchType: "Championship Match",
        championship: "AEW World Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Toni Storm",
        wrestler2: "Mariah May",
        matchType: "Championship Match",
        championship: "AEW Women's World Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Casino Battle Royal Winner",
        wrestler2: "",
        matchType: "Men's Casino Battle Royal",
        winner: null,
        participantCount: 21,
      },
    ],
  },

  NJPW: {
    eventName: "Wrestle Kingdom 19 2025",
    matches: [
      {
        wrestler1: "Kazuchika Okada",
        wrestler2: "Will Ospreay",
        matchType: "Championship Match",
        championship: "IWGP World Heavyweight Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Hiroshi Tanahashi",
        wrestler2: "Jay White",
        matchType: "Hair vs Hair Match",
        winner: null,
        participantCount: 2,
      },
    ],
  },

  TNA: {
    eventName: "Bound for Glory 2025",
    matches: [
      {
        wrestler1: "Moose",
        wrestler2: "Eddie Edwards",
        matchType: "Championship Match",
        championship: "TNA World Championship",
        winner: null,
        participantCount: 2,
      },
      {
        wrestler1: "Ultimate X Winner",
        wrestler2: "",
        matchType: "Ultimate X Match",
        winner: null,
        participantCount: 6,
      },
    ],
  },

  ROH: {
    eventName: "Death Before Dishonor 2025",
    matches: [
      {
        wrestler1: "Jonathan Gresham",
        wrestler2: "Bandido",
        matchType: "Championship Match",
        championship: "ROH World Championship",
        winner: null,
        participantCount: 2,
      },
    ],
  },
}
